export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const TRY_LOGIN = 'TRY_LOGIN';
export const TRY_REGISTERR = 'TRY_REGISTERR';
export const REGISTERR_FAILURE = 'REGISTERR_FAILURE';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const TOGGLE_LOGIN_DIALOG = 'TOGGLE_LOGIN_DIALOG';
